os: osx
osx_image: xcode9.2
language: generic

env:
  - secure: "o61wWIlIz/eL1sZxeGpUtQu1r1sBVtiz1QRRrxlaf15yFLcP1nQUQicIybTamPwT0uk667vxCo6dg42xyF71hQW9Z8abwFBQMUwozejUUULK+RmEe3BB8fsheM0b03fIsvVriKn0+S0iY9exi2Thb4tVLNUQUvsDoSSCaFXEeWmUEA0Bm7/ADAiLp+BT14gocgT77joqAIioCALiSSekG9rQTPlARH0l6UcGP0G3GB8Xflmy6/YdRLvSMvL3wm1IeW34e/Chu76iua0OIIyOPGH3/OuEdPGcBYOT2gjfEVkMptAQmWK1glwwqcFBXG6zS0itcz8ypZs6y5g6KWjHqMskMS2890bV6DQSLcl07sfOVzTF9og0qaEkjqZAXr5FZ9bgqgvw9cZdCAf/tP/0S2YqSaKSP5gSxjdcn8kW90itP5TvnFtdYz4nKIYG5nXZnCbA+AJtmz3EPzN/z7PKWYor8jRhBC+UaGfUjYlHWGg+e9ooADCUPu2uFGrh8s2wpHNdCnG1qILBJnNGHxtH0tQXJH4gkP9RIu1DVmLv48oCYFwecBn0rllbzinPQXRLABPP8THDtUjTrWh6c3Uv0fi7pZNVPiRh0fEKbrX7Soqgio/SZ9QeMxJqG5ducgUT79SvsfL2JVO/VhUUZJncfuqIGv4gXkM6kCdFME31wRo="

install:
  - ./.travis/install.sh

before_script:
  - ./.travis/build_externals.sh

script:
  - ./.travis/run.sh

notifications:
  slack:
    - secure: "i/etLbImQCsKnjrcWyKV4RPkfxeVeC6hCqrz+L3U6hkEt2P7qmXcEfeOxmiBu3MCm6ZW/JRm2EUhQYz5tJIxE8o+FhYQQsl9t/ler97lbbjgleBtkBoq48ONfBfi2FnU1leZAARTqD+CWUkAXk7BB3ZA5Zdf/+7FGXkpznNvC4yHdvl6n44RUlFArV7ceyVtUElqZh2QUbK5OEHw3yXbtraWYfHmBIN4oZmwk3ttYsV9joxCIQNgaD/eNQFF4ye9XQebWQ9o+kKgkS/eL1Nyjk117Vxx4PVcTwlJDQIpznAkFz/ZGRnL92YHaH7ZsQEr8u1Mkkvxc7Jme6+p13IorKNgH7yhAl+pM0q3Syc5ntYLF4ynYKyQgbm4C0JiLxCvHyXOHZEojeQZSthQr4+4D7RDbjeBQDNY8IPdtYbFjp/Ams0+SujpNiNuybLlTi4wkXFvL5vVuTeXn+Jg6mcm+XlLK216ymdoNLwtQKEFOz3wBplAdtgVfHh55U58ME7MPlxDf8kRzYeWJDRg1XJ8FvhPXrjApcelP58ocXj6Ng9cxZKUKERMQBCJ/D/fUKvHsp8edw6pSIOnkwHAS+539At8Yf2r9XvRYICVVwdpXqidDQh/Cm8PbD62hnrkQ7lRWfl9O0GYPTeqb/8ClS/diLB2Wcyql5oAHw436E8TZHE="
